<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class NotesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('notes')->delete();
        
        \DB::table('notes')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Odio et non.',
                'content' => 'Cumque et sequi dolores placeat saepe ut. Sequi odit provident sit autem necessitatibus. Perspiciatis aut ullam voluptatibus quia blanditiis eum omnis.',
                'note_type' => 'autem',
                'applies_to_date' => '2010-12-19',
                'users_id' => 7,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Quos ipsum quo.',
                'content' => 'Quos aut temporibus vel corporis odio enim dolor atque. Repudiandae tempora animi et dolores rerum rerum libero voluptatibus. Et odio numquam perspiciatis quod voluptates necessitatibus non repellat. Consequatur voluptatem provident laborum eos. Modi ex dolor et est magni.',
                'note_type' => 'harum',
                'applies_to_date' => '1974-10-15',
                'users_id' => 4,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Fugiat voluptatem dolorem.',
                'content' => 'Nihil vel placeat omnis quae sit quo non quas. Aut commodi voluptates hic voluptatem neque magnam. Optio ut et quia incidunt praesentium et.',
                'note_type' => 'omnis',
                'applies_to_date' => '1973-03-21',
                'users_id' => 7,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Ut et odit quod vel aut.',
                'content' => 'Porro voluptates qui ut reprehenderit accusantium nisi culpa. Reiciendis iusto ducimus dolores doloribus. Repellat est dolores est nisi fuga. Iure consequatur non eveniet hic minus necessitatibus ut.',
                'note_type' => 'suscipit natus',
                'applies_to_date' => '2001-02-19',
                'users_id' => 8,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Ratione vitae itaque.',
                'content' => 'Voluptatibus adipisci nobis nihil incidunt quo. Perspiciatis sunt dolore sed qui non ea. Placeat hic corporis aliquam quisquam. Ipsa mollitia fugiat voluptatem alias omnis.',
                'note_type' => 'consectetur',
                'applies_to_date' => '1974-04-01',
                'users_id' => 5,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Sed fuga quia nihil.',
                'content' => 'Sapiente et iste consequatur corporis explicabo enim maxime. Laborum error optio voluptatem fugiat. Cumque rerum odio sit quia ea placeat. Voluptatem quia voluptates excepturi omnis cumque modi. Nobis non illo corrupti non autem quod voluptatem et.',
                'note_type' => 'assumenda',
                'applies_to_date' => '1972-04-03',
                'users_id' => 2,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Eos animi excepturi soluta.',
                'content' => 'Voluptas et qui ad vel omnis et. Ab aut non voluptatem facilis. Mollitia voluptate molestiae quo eligendi est est est.',
                'note_type' => 'rerum sunt',
                'applies_to_date' => '2019-08-10',
                'users_id' => 6,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Vel qui aut modi omnis cupiditate.',
                'content' => 'Incidunt ducimus consectetur cumque aut eos. Et provident praesentium vel. Facilis quisquam exercitationem velit velit in dolorem. Facere id id rem facilis facilis.',
                'note_type' => 'aut',
                'applies_to_date' => '1973-01-06',
                'users_id' => 9,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Repellendus illum vitae voluptatem nam.',
                'content' => 'Similique rem occaecati tempora exercitationem eius mollitia. Aliquam fugit modi et sunt dolore accusantium accusamus. Architecto aut non numquam repudiandae consequuntur odit aut.',
                'note_type' => 'quisquam rerum',
                'applies_to_date' => '1993-12-10',
                'users_id' => 3,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Voluptas dicta quod magni ad.',
                'content' => 'Pariatur ipsum ad architecto at aut. Voluptate quis eum quo nemo et quod. Et non nesciunt iste laborum voluptatum autem. Dolores illo ratione ut cumque error.',
                'note_type' => 'est enim',
                'applies_to_date' => '1984-04-11',
                'users_id' => 8,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Est labore et ullam quo.',
                'content' => 'Porro accusamus esse eligendi ipsa est rerum inventore. Id sit quam itaque mollitia temporibus sunt. Rem voluptate ipsam voluptas aut aut incidunt nesciunt.',
                'note_type' => 'eos',
                'applies_to_date' => '1973-01-06',
                'users_id' => 5,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Ea omnis neque nesciunt.',
                'content' => 'Totam aut vel voluptas quisquam sed. Hic quo ea ipsa eum veniam eum culpa dolores. Error qui asperiores enim occaecati et. Officia dolorem cum et dolore ea est quae impedit.',
                'note_type' => 'pariatur',
                'applies_to_date' => '1996-04-15',
                'users_id' => 11,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Officia at sed sed quis ipsa.',
                'content' => 'Odit reprehenderit nihil voluptas est. Id dolore accusamus voluptatibus quo excepturi ad. Sed ipsum quod quisquam. Exercitationem corrupti laborum voluptatem iure debitis.',
                'note_type' => 'dicta asperiores',
                'applies_to_date' => '2019-09-29',
                'users_id' => 5,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'A ut esse explicabo et.',
                'content' => 'Quasi mollitia fuga laboriosam consectetur fuga officiis reiciendis dolor. Sequi amet odio veniam quibusdam eaque.',
                'note_type' => 'in deserunt',
                'applies_to_date' => '1977-10-04',
                'users_id' => 5,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Dolorem perferendis et distinctio.',
                'content' => 'Nihil qui aut ut. Reiciendis error dolorem eos facilis aut ipsum numquam.',
                'note_type' => 'enim ea',
                'applies_to_date' => '1983-10-09',
                'users_id' => 3,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Quod nobis dolores modi possimus.',
                'content' => 'Debitis in illo voluptatem atque ad. Tempora maxime et qui molestias eius. Quidem autem aliquam sed maiores.',
                'note_type' => 'consectetur',
                'applies_to_date' => '2006-06-03',
                'users_id' => 9,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Sunt rerum reprehenderit.',
                'content' => 'Quia corrupti aut ut ducimus earum nam. Illum autem id consectetur aperiam voluptatem non non magnam. Est aut et officiis nostrum nostrum nostrum assumenda.',
                'note_type' => 'rerum',
                'applies_to_date' => '2011-01-26',
                'users_id' => 9,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Cupiditate nesciunt minima est.',
                'content' => 'Porro sint magnam sed veritatis. Iure commodi exercitationem nemo aliquam voluptate aliquid. Cum dicta aut vitae eaque.',
                'note_type' => 'quos cumque',
                'applies_to_date' => '2007-06-19',
                'users_id' => 10,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Voluptatem est porro praesentium ut.',
                'content' => 'Aliquid et voluptas sed. Qui consectetur ut et voluptas illo distinctio. Occaecati ratione ut molestiae labore fugiat et dolores. Quam quis sint voluptatem amet debitis id eos quos.',
                'note_type' => 'numquam',
                'applies_to_date' => '1979-02-05',
                'users_id' => 4,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Deserunt inventore ut est.',
                'content' => 'Quo dolor maiores nemo harum. Odio quidem ullam recusandae dolor. Quia atque totam est architecto reprehenderit.',
                'note_type' => 'optio',
                'applies_to_date' => '1973-06-02',
                'users_id' => 5,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'Architecto culpa quibusdam.',
                'content' => 'Ipsa quam quasi qui dolorem eius tenetur nihil. Id magnam id iusto consectetur ut quia autem quia. Ipsum aut recusandae ut quia ipsum.',
                'note_type' => 'ut non',
                'applies_to_date' => '2017-11-30',
                'users_id' => 9,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'Amet est ullam sit odit sit.',
                'content' => 'Sint aut eius qui nihil. Sint possimus vero voluptatibus ipsa maxime. Ut inventore et sit autem error. Minus amet praesentium est quo deleniti mollitia et harum.',
                'note_type' => 'perferendis et',
                'applies_to_date' => '1980-10-13',
                'users_id' => 11,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'Reiciendis eveniet ad exercitationem.',
                'content' => 'Iusto dicta et exercitationem dolorem odio nihil itaque. Ut voluptatem expedita ea voluptatem sed. Laboriosam similique soluta omnis natus optio. Deserunt et dolorum sint ad aspernatur nihil velit.',
                'note_type' => 'impedit sint',
                'applies_to_date' => '2016-07-09',
                'users_id' => 4,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'Rerum modi alias aut quod.',
                'content' => 'Qui amet sunt ad dicta. Numquam iusto et iusto ipsam consectetur consequatur et sed. Ducimus saepe iusto non et illo ut itaque.',
                'note_type' => 'culpa fugiat',
                'applies_to_date' => '2021-10-23',
                'users_id' => 9,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'Quasi officiis quidem.',
                'content' => 'Voluptatum voluptatum temporibus omnis voluptas eius sit labore. Aut et sed et non. Eligendi eum mollitia sit quidem voluptate voluptates.',
                'note_type' => 'enim',
                'applies_to_date' => '1978-05-06',
                'users_id' => 9,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'Doloremque sunt molestiae nihil.',
                'content' => 'Sunt qui odit veniam laborum ea accusantium sunt. Velit omnis omnis non architecto sequi iste et voluptates. Tempora aut explicabo ut omnis nisi perferendis maxime odit. Temporibus placeat provident inventore et quis nihil nesciunt. Qui omnis ut dignissimos aut.',
                'note_type' => 'sit eaque',
                'applies_to_date' => '1998-06-18',
                'users_id' => 7,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'Dignissimos cum autem ducimus autem.',
                'content' => 'Totam exercitationem nostrum veritatis quia est maiores id natus. Voluptatem quisquam accusamus qui eligendi ipsam vel assumenda. Dolorem enim vel qui.',
                'note_type' => 'et',
                'applies_to_date' => '1977-09-20',
                'users_id' => 6,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'Incidunt et voluptas consequatur dolore.',
                'content' => 'Iste quaerat et earum quo eligendi neque. Suscipit error deleniti iusto officia fugiat. Cum nobis ullam illo ipsam. Ut necessitatibus autem eum eos consequatur omnis. Architecto molestiae optio natus architecto natus totam.',
                'note_type' => 'quia dolores',
                'applies_to_date' => '2009-05-27',
                'users_id' => 11,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'Reiciendis minus id consequatur.',
                'content' => 'Voluptatem quos inventore quae tenetur. Et fugiat non facilis sequi aspernatur et libero.',
                'note_type' => 'a',
                'applies_to_date' => '2019-02-13',
                'users_id' => 2,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'Non ea aut aut omnis nostrum.',
                'content' => 'Et inventore ea natus voluptatibus suscipit. Accusamus iure voluptatem debitis ut aliquid eius eum ad. Maiores totam eum mollitia eum similique. Doloremque maxime qui reiciendis temporibus repellendus asperiores suscipit.',
                'note_type' => 'labore',
                'applies_to_date' => '2019-02-20',
                'users_id' => 6,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'Beatae cupiditate iusto aperiam.',
                'content' => 'Iusto et et sed incidunt a est doloremque vel. Sequi non neque in delectus sunt. Ut enim distinctio enim exercitationem placeat dolorem.',
                'note_type' => 'quia',
                'applies_to_date' => '1994-05-07',
                'users_id' => 9,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'Hic unde hic.',
                'content' => 'Assumenda reiciendis ducimus aut earum a. Vel iure et accusantium eum in. Et officiis blanditiis omnis dolorum.',
                'note_type' => 'sint',
                'applies_to_date' => '2003-09-18',
                'users_id' => 2,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'Et possimus alias optio possimus provident.',
                'content' => 'Laborum aperiam quis provident. Debitis enim vero reprehenderit reiciendis architecto quidem. Est unde alias et.',
                'note_type' => 'sapiente est',
                'applies_to_date' => '2018-04-29',
                'users_id' => 10,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'Sed adipisci nobis veritatis.',
                'content' => 'Assumenda et recusandae eos. Ipsam facere quia sint non.',
                'note_type' => 'officiis',
                'applies_to_date' => '2000-11-29',
                'users_id' => 6,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'Et aliquam aperiam beatae qui quisquam.',
                'content' => 'Aut aut nulla nihil similique exercitationem. Magni incidunt neque repudiandae tenetur. Eos quis vitae aut et eos odio qui.',
                'note_type' => 'quam',
                'applies_to_date' => '2020-04-14',
                'users_id' => 11,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'Excepturi perferendis odit ab.',
                'content' => 'Aut a corrupti consequatur et quos deserunt. Corrupti et voluptatum ex earum. Vitae quis ipsa impedit.',
                'note_type' => 'velit',
                'applies_to_date' => '1998-09-24',
                'users_id' => 6,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'Quos exercitationem delectus alias eum nesciunt.',
                'content' => 'Magni voluptas quo asperiores quia at qui autem. Eum dicta et quia totam exercitationem. Ratione rerum dolorem et consectetur dolor.',
                'note_type' => 'eaque ut',
                'applies_to_date' => '2021-08-24',
                'users_id' => 11,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'title' => 'Expedita consequatur eaque.',
                'content' => 'Voluptatem iste saepe numquam est pariatur et blanditiis eos. Aspernatur excepturi temporibus eum et laudantium qui officia. Dolorum impedit doloribus veritatis aliquam. Voluptatum non sapiente veniam doloremque libero voluptatum.',
                'note_type' => 'aut molestiae',
                'applies_to_date' => '1977-05-17',
                'users_id' => 7,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'title' => 'Quo omnis incidunt et placeat sed.',
                'content' => 'In eos iste est blanditiis ipsam totam iure ut. Molestias laboriosam explicabo et. Quisquam voluptatem vero sequi consequatur dignissimos et. Nostrum incidunt dolore est pariatur.',
                'note_type' => 'voluptas repellendus',
                'applies_to_date' => '1999-07-19',
                'users_id' => 3,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'title' => 'Sunt cupiditate pariatur unde.',
                'content' => 'Dolorem nisi quas sed reprehenderit nulla ducimus. Placeat rerum voluptas et porro omnis et non. Ut doloribus quam ea veritatis. Et omnis earum recusandae doloribus laudantium aspernatur.',
                'note_type' => 'explicabo',
                'applies_to_date' => '2000-12-26',
                'users_id' => 4,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'title' => 'Voluptas quia voluptatem.',
                'content' => 'Id qui repellat est quis labore est delectus aspernatur. Quia reiciendis voluptatem eius voluptatum et unde. Natus aspernatur quis ullam aliquid laboriosam dolore voluptatem. Qui exercitationem totam quo commodi vel aut temporibus autem.',
                'note_type' => 'aliquam distinctio',
                'applies_to_date' => '1970-12-24',
                'users_id' => 7,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'title' => 'Saepe recusandae facilis molestiae numquam ea.',
                'content' => 'Itaque qui magni alias maxime molestias ducimus sunt. Architecto eos voluptas eum et nesciunt voluptate suscipit. Ipsa et omnis doloremque ut et voluptates in. At vero itaque velit est odio aspernatur ut.',
                'note_type' => 'sint quia',
                'applies_to_date' => '1975-04-14',
                'users_id' => 4,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'title' => 'Aliquid voluptas natus.',
                'content' => 'At cupiditate sed illum non facere vel. Rerum omnis dolorem a rerum dignissimos maiores amet. Placeat possimus explicabo atque pariatur asperiores. Ea provident necessitatibus iste repellat explicabo quis et.',
                'note_type' => 'delectus consequatur',
                'applies_to_date' => '1971-04-23',
                'users_id' => 10,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'title' => 'Voluptatem magnam iusto ut.',
                'content' => 'Beatae et et rerum. Sequi eos praesentium reiciendis voluptatem aut. Quia velit quod cupiditate doloremque dignissimos.',
                'note_type' => 'provident quibusdam',
                'applies_to_date' => '1990-03-01',
                'users_id' => 7,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'title' => 'Est aut corrupti dolorem.',
                'content' => 'Ut consequatur accusantium molestiae quibusdam consequatur consequuntur ut fugit. Officiis necessitatibus possimus eligendi natus est error. Autem non sed eos sit qui repudiandae impedit.',
                'note_type' => 'est',
                'applies_to_date' => '1983-01-21',
                'users_id' => 5,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'title' => 'Quaerat repudiandae rem sit voluptatum.',
                'content' => 'Suscipit illum iusto eum. Possimus et sed fugiat aspernatur expedita cumque. Voluptatem dolorem esse explicabo qui maxime. Perferendis numquam ea nulla dolorem velit ex.',
                'note_type' => 'aspernatur quas',
                'applies_to_date' => '2008-05-12',
                'users_id' => 9,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'title' => 'Quo architecto possimus.',
                'content' => 'Perspiciatis sequi placeat eos dolore quo. Rerum distinctio est non doloremque sed iusto id. Reprehenderit natus voluptatum sunt cum vel.',
                'note_type' => 'atque',
                'applies_to_date' => '1982-08-26',
                'users_id' => 8,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'title' => 'Et dolorem libero.',
                'content' => 'Enim quia enim possimus ut ut. Et quisquam omnis illo architecto odit quos et. Quis nesciunt eos nihil ab. Dolore excepturi qui vitae autem quam.',
                'note_type' => 'accusantium',
                'applies_to_date' => '2021-11-12',
                'users_id' => 10,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'title' => 'Corrupti sint consequatur est odit odit.',
                'content' => 'Quos voluptate est officia velit doloremque quo. Aut aut praesentium ipsa magni. Quas laudantium cum assumenda alias aut repudiandae sit.',
                'note_type' => 'impedit tempora',
                'applies_to_date' => '2013-03-28',
                'users_id' => 5,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'title' => 'Nam molestiae quisquam.',
                'content' => 'Ut officiis voluptas eum cumque quia dolor. Libero quaerat magni aut est aut sit repellendus. Labore ipsum quam placeat ea repellat.',
                'note_type' => 'voluptatem',
                'applies_to_date' => '2000-11-23',
                'users_id' => 3,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'title' => 'Repellendus aliquam distinctio quod.',
                'content' => 'Dolorem distinctio consequatur vitae in. Sed dolorem qui nihil deleniti vero possimus iste. Inventore unde saepe accusamus cumque. Voluptatibus qui natus optio nemo quis ut qui qui.',
                'note_type' => 'fugiat aut',
                'applies_to_date' => '2018-02-15',
                'users_id' => 2,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'title' => 'Dolor quam nesciunt dolorem nam.',
                'content' => 'Beatae debitis officiis quas veniam odio. Voluptatem animi eaque magnam neque tenetur est. Dolore ut debitis sint ut doloribus. Voluptatem vitae et quis est repellat et qui et.',
                'note_type' => 'nobis',
                'applies_to_date' => '2014-07-30',
                'users_id' => 2,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'title' => 'Quasi soluta illum molestiae sunt.',
                'content' => 'Quae ratione repudiandae vel reiciendis. Esse maiores et ea pariatur omnis molestiae. A labore aut tempore quis voluptas soluta. Maxime sint cum unde iusto iste. Impedit quam molestiae beatae provident.',
                'note_type' => 'fugit in',
                'applies_to_date' => '1984-06-01',
                'users_id' => 4,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'title' => 'Fugiat veniam et.',
                'content' => 'Velit est et recusandae quia non architecto molestiae. Mollitia ea ab facilis voluptatibus iure quaerat non. Est sunt similique nam non. Est consequatur aut ullam aperiam.',
                'note_type' => 'itaque',
                'applies_to_date' => '2020-01-26',
                'users_id' => 5,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'title' => 'Ullam optio iste porro saepe.',
                'content' => 'Nobis ex et est qui alias. Possimus quaerat aut deserunt in autem sit molestias. Fugit est perferendis minima est laborum aliquam. Et et dolor occaecati inventore quia molestias. Maxime autem autem architecto consectetur.',
                'note_type' => 'corporis',
                'applies_to_date' => '2003-03-26',
                'users_id' => 3,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'title' => 'Odit aut illo explicabo officia nemo.',
                'content' => 'Numquam quam ad laudantium error. Enim ab consequatur corporis sunt eveniet et.',
                'note_type' => 'voluptatibus officiis',
                'applies_to_date' => '1971-02-25',
                'users_id' => 4,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'title' => 'Est qui est quod.',
                'content' => 'Aut accusamus et consequatur autem enim. Nostrum nostrum atque officia itaque explicabo repellat et. Ullam sed ea laborum. Doloribus quibusdam laborum odit minus labore. Natus delectus dolorum eveniet nesciunt assumenda dolores et.',
                'note_type' => 'nihil aliquid',
                'applies_to_date' => '2016-10-23',
                'users_id' => 4,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'title' => 'Repellendus mollitia commodi nostrum veritatis.',
                'content' => 'Ab atque animi vel qui porro saepe nobis. Asperiores ut omnis aliquam dolorem quo. Nobis soluta delectus inventore. Est eveniet esse sapiente sit ut delectus consequatur nemo.',
                'note_type' => 'et nisi',
                'applies_to_date' => '2012-01-06',
                'users_id' => 11,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'title' => 'Ullam non illum provident est natus.',
                'content' => 'Eum molestiae et ut unde. Blanditiis ut est incidunt pariatur repellat corporis sint laudantium. Voluptas adipisci modi temporibus non illum accusantium minus id.',
                'note_type' => 'nesciunt',
                'applies_to_date' => '2020-08-25',
                'users_id' => 5,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'title' => 'Enim voluptates sed modi mollitia nobis.',
                'content' => 'Quaerat ad reiciendis qui ipsum quam facere. Saepe tenetur sunt fuga nemo rerum non. Molestias sunt vel non eos.',
                'note_type' => 'numquam',
                'applies_to_date' => '1992-05-17',
                'users_id' => 10,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'title' => 'Qui officia et dolorem tempore temporibus.',
                'content' => 'Quos ea nulla id quis in voluptatem illo explicabo. Possimus laudantium ut aut est quis qui. Delectus alias eligendi sed recusandae.',
                'note_type' => 'ducimus',
                'applies_to_date' => '2011-12-13',
                'users_id' => 4,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'title' => 'Ut qui dolor maxime.',
                'content' => 'Doloribus veniam dolorum in voluptatem tempora facilis eum. Aut sint similique aut laborum provident excepturi.',
                'note_type' => 'dolor odio',
                'applies_to_date' => '1975-11-08',
                'users_id' => 8,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'title' => 'Sequi ipsa harum asperiores libero aliquid.',
                'content' => 'Similique velit voluptatem at praesentium inventore optio. Odio ipsam consequuntur et exercitationem est delectus dolores modi. Beatae quas ab delectus dignissimos fugiat. Et et laborum modi maiores asperiores quibusdam. Ipsum ullam aut magni natus unde nostrum odio.',
                'note_type' => 'ut et',
                'applies_to_date' => '1977-04-10',
                'users_id' => 5,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'title' => 'Atque ea saepe at eaque.',
                'content' => 'Veritatis voluptatem molestiae odio quibusdam excepturi quas. Corporis architecto et rerum dolor odit. Facere quam voluptas quia dolorum. Placeat impedit consequatur aut.',
                'note_type' => 'soluta',
                'applies_to_date' => '2003-01-31',
                'users_id' => 10,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'title' => 'Architecto odio voluptatem vel nostrum officiis.',
                'content' => 'Sunt ut consectetur exercitationem eaque architecto nemo. Enim mollitia dolor vel harum ut nemo.',
                'note_type' => 'dolore',
                'applies_to_date' => '1973-05-06',
                'users_id' => 2,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'title' => 'Ut ea nihil accusantium.',
                'content' => 'Et sapiente atque velit et molestiae iure veniam. Sapiente accusantium tempora officia iure odio nam eum culpa. Quasi corporis aut similique repellendus impedit ex provident totam.',
                'note_type' => 'sit',
                'applies_to_date' => '1992-02-17',
                'users_id' => 3,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'title' => 'Aut quos non.',
                'content' => 'Mollitia sint aliquid soluta ratione est in reiciendis suscipit. Hic voluptatem animi et asperiores dolore autem cum nesciunt. Sit omnis sunt et explicabo rerum hic ut. Modi neque iusto atque rerum possimus.',
                'note_type' => 'impedit',
                'applies_to_date' => '1973-10-20',
                'users_id' => 5,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'title' => 'Vero laborum molestias.',
                'content' => 'Explicabo nesciunt libero sunt repellendus aut. Pariatur suscipit qui in provident iste. Dignissimos id facilis deserunt rerum natus est ipsam. Molestiae illo nisi eum iusto. Qui accusantium quod fugit vitae alias.',
                'note_type' => 'voluptatum ex',
                'applies_to_date' => '1978-05-22',
                'users_id' => 2,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'title' => 'Cupiditate quae ad voluptas ullam.',
                'content' => 'Dolorum magni soluta soluta qui mollitia fugiat rerum. Incidunt velit deleniti laudantium sed. Possimus rem voluptates numquam non. Qui velit nam qui omnis optio nulla. Mollitia cupiditate ut dolores animi explicabo iure et.',
                'note_type' => 'sit dolores',
                'applies_to_date' => '1999-12-21',
                'users_id' => 3,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'title' => 'Dolores doloremque harum corporis corporis.',
                'content' => 'Voluptatem in corporis laborum amet ut deleniti. Aliquid ab qui rerum delectus facilis. Harum voluptatem non quo quis neque.',
                'note_type' => 'incidunt',
                'applies_to_date' => '1979-02-05',
                'users_id' => 11,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'title' => 'Temporibus vel ratione aliquam cupiditate.',
                'content' => 'Impedit qui ipsam cum quam non. Hic adipisci ut tempore voluptate facilis. Temporibus quia quibusdam aut magnam.',
                'note_type' => 'veritatis',
                'applies_to_date' => '2011-04-19',
                'users_id' => 7,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'title' => 'Ut assumenda ut aliquam.',
                'content' => 'Ducimus fuga odit eligendi temporibus. Id ab animi qui veritatis architecto.',
                'note_type' => 'est laborum',
                'applies_to_date' => '2012-11-20',
                'users_id' => 5,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'title' => 'Consequatur libero aut voluptas velit.',
                'content' => 'Aut eius ut dolore nihil dolores. Illum nihil aut et tempore. Laborum distinctio et esse sunt odio ut velit.',
                'note_type' => 'fugit vero',
                'applies_to_date' => '2000-07-27',
                'users_id' => 2,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'title' => 'Repudiandae voluptatem perferendis velit maiores dignissimos.',
                'content' => 'Aliquid quia iure adipisci consectetur reprehenderit consequuntur. In earum labore dignissimos aut aut voluptatibus fuga et. Non velit officiis nam laudantium dolorum. Quisquam voluptas aliquam deleniti sit earum sapiente cumque aspernatur.',
                'note_type' => 'sint',
                'applies_to_date' => '2003-07-12',
                'users_id' => 7,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'title' => 'Excepturi molestias quasi ipsam atque.',
                'content' => 'Sed cumque similique ex dolores perspiciatis inventore rerum. Dolorum vitae rerum molestiae. Nihil similique non laborum ut.',
                'note_type' => 'nam neque',
                'applies_to_date' => '2016-08-30',
                'users_id' => 11,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'title' => 'Modi impedit doloremque.',
                'content' => 'Cum maxime eligendi nostrum nulla laboriosam magni dignissimos. Dolor fuga doloremque nesciunt dolorem sed et culpa. Iste modi voluptatem esse nisi aperiam accusantium.',
                'note_type' => 'maxime maxime',
                'applies_to_date' => '2014-05-24',
                'users_id' => 10,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'title' => 'Est quo qui odit.',
                'content' => 'Voluptatem sed id ut blanditiis. Doloremque est eum sit et aliquam. Consequatur sunt error temporibus quia voluptatem hic suscipit.',
                'note_type' => 'et vel',
                'applies_to_date' => '2009-04-16',
                'users_id' => 9,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'title' => 'In ut voluptate ratione.',
                'content' => 'Aut est quibusdam cumque ullam. Ipsam assumenda aspernatur pariatur cumque aliquam est. Accusamus praesentium repellat est id harum porro amet.',
                'note_type' => 'qui',
                'applies_to_date' => '2007-05-18',
                'users_id' => 9,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'title' => 'Commodi voluptatibus optio repudiandae quas rem.',
                'content' => 'Est odio nulla facere laudantium. Cupiditate cumque eligendi est nisi. Molestias corrupti a provident et. Omnis suscipit ratione possimus.',
                'note_type' => 'eos',
                'applies_to_date' => '2022-04-19',
                'users_id' => 10,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'title' => 'Eligendi aliquid vel accusantium in.',
                'content' => 'Et excepturi voluptas nostrum id nesciunt quibusdam. Atque quia accusamus deserunt aut quis. Quibusdam commodi quam alias fugiat qui ut quia voluptatem.',
                'note_type' => 'nesciunt',
                'applies_to_date' => '1993-04-16',
                'users_id' => 5,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'title' => 'Qui et error consequatur.',
                'content' => 'Et repellat harum et accusantium autem. Ut inventore minus laudantium architecto. Accusamus error deserunt hic tempore occaecati.',
                'note_type' => 'quis nam',
                'applies_to_date' => '1985-09-23',
                'users_id' => 2,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'title' => 'Quo est deserunt ut quaerat.',
                'content' => 'Ab explicabo et magnam et dolor. Atque omnis provident nesciunt voluptatibus alias inventore. Voluptatum qui nisi enim voluptatem rerum consectetur accusantium mollitia. Repellendus sapiente aliquam et eveniet.',
                'note_type' => 'nostrum quo',
                'applies_to_date' => '2001-06-21',
                'users_id' => 3,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'title' => 'Expedita facilis est mollitia.',
                'content' => 'Recusandae quidem dolor asperiores velit repudiandae. Culpa mollitia eaque qui. Voluptatibus velit id id non voluptas. Ut accusamus culpa eos provident aut cupiditate.',
                'note_type' => 'iure',
                'applies_to_date' => '2019-01-14',
                'users_id' => 3,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'title' => 'Impedit dolorum rerum voluptatum.',
                'content' => 'Vel id qui qui sunt. Dolorum iure quam dolore quod.',
                'note_type' => 'quaerat eos',
                'applies_to_date' => '1998-09-05',
                'users_id' => 6,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'title' => 'Est nostrum sunt error.',
                'content' => 'Harum aut hic ratione praesentium. Mollitia delectus placeat veritatis veniam minima. Culpa voluptatem soluta sed earum quo debitis aperiam. Ea sunt hic tenetur nam dolor labore consequatur.',
                'note_type' => 'omnis',
                'applies_to_date' => '2017-05-12',
                'users_id' => 8,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'title' => 'Tempore est omnis et qui.',
                'content' => 'Adipisci qui consequatur id repudiandae. Quia reprehenderit sit omnis consectetur eaque. Expedita nulla voluptates neque consequatur ullam culpa est. Voluptas qui ad repellendus excepturi nihil sapiente dolor.',
                'note_type' => 'qui natus',
                'applies_to_date' => '1979-01-29',
                'users_id' => 11,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'title' => 'Et rerum eius dignissimos et.',
                'content' => 'At dolores accusantium odit molestiae perspiciatis libero sequi. Fugiat quo aperiam dolore. Eaque est architecto est aut mollitia. Ut quia ducimus aperiam.',
                'note_type' => 'et quasi',
                'applies_to_date' => '1987-01-25',
                'users_id' => 9,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'title' => 'Nesciunt aut eum quas ea veritatis.',
                'content' => 'Eum magni rerum dolores aliquam iusto. Inventore perspiciatis totam enim mollitia. Cumque quod ullam in. Aut earum qui reprehenderit molestiae est. Dicta eveniet excepturi sunt aspernatur vel dolorum esse voluptatem.',
                'note_type' => 'ducimus nihil',
                'applies_to_date' => '2011-12-11',
                'users_id' => 6,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'title' => 'Excepturi cupiditate dolor possimus nisi.',
                'content' => 'Eos quia illum voluptate tempore necessitatibus pariatur eligendi quaerat. Quod et aspernatur dolorem ipsa facilis sed modi. Provident maxime consequatur quaerat voluptatem dignissimos aut itaque. Iusto doloribus iure itaque consequuntur vero. Eos et omnis voluptatem.',
                'note_type' => 'tempora dignissimos',
                'applies_to_date' => '1997-03-20',
                'users_id' => 10,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'title' => 'Est sed qui quia.',
                'content' => 'Qui aut incidunt quia. Qui temporibus voluptas velit eos voluptatem corrupti.',
                'note_type' => 'quas quidem',
                'applies_to_date' => '2018-01-10',
                'users_id' => 6,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'title' => 'Aliquid molestias blanditiis illo dolorem accusamus.',
                'content' => 'Est adipisci et architecto modi velit. Ut architecto tenetur deleniti quaerat. Nostrum officia consequatur ut animi.',
                'note_type' => 'ut',
                'applies_to_date' => '2017-02-07',
                'users_id' => 5,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'title' => 'Ducimus minus quo inventore delectus voluptatem.',
                'content' => 'Consequuntur autem maxime eligendi accusamus quae et vero. Unde quos aliquid cupiditate incidunt rem repudiandae. Facere debitis eaque autem ut odio occaecati doloribus. Quae repellendus numquam placeat ut commodi.',
                'note_type' => 'ipsum et',
                'applies_to_date' => '1988-01-24',
                'users_id' => 8,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'title' => 'Explicabo dolor occaecati fugiat minima ducimus.',
                'content' => 'Odit ut laborum sequi explicabo. In eligendi ea quas fugit est et eum. Ea facere vero quo deserunt. Inventore ullam error autem molestiae quidem et pariatur.',
                'note_type' => 'soluta',
                'applies_to_date' => '2013-03-13',
                'users_id' => 9,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'title' => 'Amet voluptas earum repellat.',
                'content' => 'Officia aperiam ab autem repellendus. At quae sed voluptas aut magni eaque. Repellendus ut delectus minima. Voluptates saepe et sunt.',
                'note_type' => 'culpa aliquid',
                'applies_to_date' => '2004-08-19',
                'users_id' => 2,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'title' => 'Natus consectetur id.',
                'content' => 'Id facilis repellat qui alias ipsum quos voluptatem consequuntur. Hic officia facere enim sed repudiandae quia. Rerum repudiandae qui dolorem sunt.',
                'note_type' => 'delectus molestiae',
                'applies_to_date' => '1980-07-05',
                'users_id' => 4,
                'status_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'title' => 'Sint perspiciatis modi facere beatae.',
                'content' => 'Assumenda quam nihil vel. Minus dolorum aliquid consequuntur a.',
                'note_type' => 'beatae',
                'applies_to_date' => '1985-09-28',
                'users_id' => 10,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'title' => 'Aliquid nam rem dolorem.',
                'content' => 'Vero similique placeat aut excepturi necessitatibus provident ex. Aut voluptate et optio et quibusdam ea natus. Nisi culpa officiis est quae tempore incidunt.',
                'note_type' => 'consequatur',
                'applies_to_date' => '1987-05-13',
                'users_id' => 4,
                'status_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'title' => 'Recusandae voluptas qui blanditiis.',
                'content' => 'Totam nihil exercitationem minus. Mollitia vel sed nihil autem hic voluptatem consequuntur. Laudantium quo ex dicta libero aut hic. Exercitationem officiis quo distinctio omnis velit.',
                'note_type' => 'nihil odio',
                'applies_to_date' => '2007-07-23',
                'users_id' => 6,
                'status_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'title' => 'Et facere laborum et.',
                'content' => 'Beatae repudiandae eum cupiditate recusandae. Et eaque voluptatem repellat in ut sunt non.',
                'note_type' => 'praesentium',
                'applies_to_date' => '2012-10-29',
                'users_id' => 3,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'title' => 'Necessitatibus fugiat velit voluptatem.',
                'content' => 'Dolores eum consequatur totam aliquam corrupti ducimus vel. Exercitationem illo sit dicta assumenda corporis maxime. Excepturi libero ratione sed ea earum eius officiis suscipit. Aliquam dolorem est quaerat numquam.',
                'note_type' => 'amet',
                'applies_to_date' => '2021-04-01',
                'users_id' => 5,
                'status_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}