<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_items')->delete();
        
        \DB::table('product_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category_id' => 4,
                'subcategory_id' => 1,
                'created_at' => '2023-06-09 12:39:17',
                'updated_at' => '2023-06-19 14:55:56',
                'status' => 1,
                'promotional' => 1,
                'name' => 'Long Hair',
                'unitprice' => '15.0',
                'imgurl' => 'https://res.cloudinary.com/beleza-na-web/image/upload/w_100,f_auto,fl_progressive,q_auto:best/v1/imagens/5/kerastase-densifique-bain-densite-shampoo-250ml-46916-8788758772485934401.jpg',
                'obs' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'category_id' => 2,
                'subcategory_id' => 1,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => '2023-06-19 14:50:07',
                'status' => 1,
                'promotional' => 1,
                'name' => 'Shampoo Antiqueda',
                'unitprice' => '7.0',
                'imgurl' => 'https://static.vecteezy.com/system/resources/previews/006/046/341/original/barbershop-logo-vintage-classic-style-salon-fashion-haircut-pomade-badge-icon-simple-minimalist-modern-barber-pole-razor-shave-scissor-razor-blade-retro-symbol-luxury-elegant-design-free-vector.jpg',
                'obs' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'category_id' => 2,
                'subcategory_id' => 2,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => '2023-06-11 01:28:21',
                'status' => 1,
                'promotional' => 1,
                'name' => 'Pizza Pepperoni',
                'unitprice' => '40.99',
                'imgurl' => 'https://www.receiteria.com.br/wp-content/uploads/receitas-de-pizza-de-pepperoni-0.jpg',
                'obs' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'category_id' => 2,
                'subcategory_id' => 2,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => '2023-06-11 01:30:17',
                'status' => 1,
                'promotional' => 0,
                'name' => 'Pizza Mix',
                'unitprice' => '11.20',
                'imgurl' => 'http://icube.milliyet.com.tr/YeniAnaResim/2016/10/24/tavada-pizza-tarifi-7857137.Jpeg',
                'obs' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'category_id' => 2,
                'subcategory_id' => 2,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 1,
                'name' => 'Neapolitan Pizza',
                'unitprice' => '12.10',
                'imgurl' => 'https://img.grouponcdn.com/deal/2SVzinBnAH17zHrq3HNpurto2gpK/2S-700x420/v1/c700x420.jpg',
                'obs' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'category_id' => 2,
                'subcategory_id' => 3,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => '2023-06-11 01:31:19',
                'status' => 1,
                'promotional' => 0,
                'name' => 'Espeto de tomate e alho',
                'unitprice' => '16.60',
                'imgurl' => 'https://images.squarespace-cdn.com/content/v1/5cbb41b0fd679350c74ea497/1624719414474-4JK4QFQCRL2X68IC3QN4/Kofta+kebabs+with+tomato+sauce+and+yogurt-garlic+sauce.jpg',
                'obs' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'category_id' => 2,
                'subcategory_id' => 3,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Adana Kebab',
                'unitprice' => '15.0',
                'imgurl' => 'http://www.muslumkebap.com/Contents/Upload/MuslumAdana_qyz0b34a.p3w.jpg',
                'obs' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'category_id' => 2,
                'subcategory_id' => 3,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Eggplant Kebab',
                'unitprice' => '18.0',
                'imgurl' => 'http://www.muslumkebap.com/Contents/Upload/MuslumPatlicanKebap_y41olk55.kpc.jpg',
                'obs' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'category_id' => 2,
                'subcategory_id' => 3,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 1,
                'name' => 'Shish Kebab',
                'unitprice' => '10.0',
                'imgurl' => 'http://2.bp.blogspot.com/-4_8T6g3qOCU/VVz3oASO5lI/AAAAAAAAUHo/rEw1XlZoxqQ/s1600/Shish.jpg',
                'obs' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'category_id' => 2,
                'subcategory_id' => 4,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Pistachio Baklava',
                'unitprice' => '10.0',
                'imgurl' => 'http://www.karakoygulluoglu.com/fistikli-kare-baklava-32-15-B.jpg',
                'obs' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'category_id' => 2,
                'subcategory_id' => 4,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Palace Pistachio Baklava',
                'unitprice' => '12.50',
                'imgurl' => 'http://www.karakoygulluoglu.com/fistikli-havuc-dilim-baklava-1kg-31-14-B.jpg',
                'obs' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'category_id' => 2,
                'subcategory_id' => 4,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Mixed Baklava in Tray',
                'unitprice' => '60.0',
                'imgurl' => 'http://www.karakoygulluoglu.com/karisik-baklava-1-tepsi-66-31-B.jpg',
                'obs' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'category_id' => 2,
                'subcategory_id' => 4,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Tel Kadayıf with Pistachio',
                'unitprice' => '9.0',
                'imgurl' => 'http://www.karakoygulluoglu.com/fistikli-tel-kadayif-1-39-44-B.jpg',
                'obs' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'category_id' => 3,
                'subcategory_id' => 5,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => '0.5 liter',
                'unitprice' => '0.30',
                'imgurl' => 'http://cdn.avansas.com/assets/59479/erikli-su-0-5-lt-12-li-1-zoom.jpg',
                'obs' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'category_id' => 3,
                'subcategory_id' => 6,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Coca Cola 0.3l',
                'unitprice' => '0.70',
                'imgurl' => 'https://images-na.ssl-images-amazon.com/images/I/818i%2BQm07UL._SL1500_.jpg',
                'obs' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'category_id' => 3,
                'subcategory_id' => 6,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Coca Cola 0.2l',
                'unitprice' => '1.0',
                'imgurl' => 'https://images-na.ssl-images-amazon.com/images/I/511rL-aYd9L._SL1000_.jpg',
                'obs' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'category_id' => 3,
                'subcategory_id' => 6,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Fanta 0.3l',
                'unitprice' => '0.70',
                'imgurl' => 'http://www.germandeli.com/product-images/Fanta-Orange-Orange-Soda-33l_main-1.jpg',
                'obs' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'category_id' => 3,
                'subcategory_id' => 6,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Fanta 0.5l',
                'unitprice' => '1.10',
                'imgurl' => 'http://www.germandeli.com/product-images/Fanta-Orange-0-5-liter-bottle_main-1.jpg',
                'obs' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'category_id' => 3,
                'subcategory_id' => 6,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Sprite 0.5l',
                'unitprice' => '1.10',
                'imgurl' => 'https://cdn.grofers.com/app/images/products/full_screen/pro_312.jpg',
                'obs' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'category_id' => 3,
                'subcategory_id' => 7,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Turkish Tea',
                'unitprice' => '20.0',
                'imgurl' => 'https://images.hepsiburada.net/assets/Taris/500/Taris_3092120.jpg',
                'obs' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'category_id' => 3,
                'subcategory_id' => 8,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Turkish Coffee',
                'unitprice' => '20.0',
                'imgurl' => 'https://cdn3.volusion.com/p3y5v.vg2ps/v/vspfiles/photos/TCW-XME02-2.jpg?1500568557',
                'obs' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'category_id' => 3,
                'subcategory_id' => 9,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Mixed Fruit Juice',
                'unitprice' => '1.0',
                'imgurl' => 'https://images.hepsiburada.net/assets/Taris/500/Taris_4791763.jpg',
                'obs' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'category_id' => 3,
                'subcategory_id' => 9,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Apricot Fruit Juice',
                'unitprice' => '1.0',
                'imgurl' => 'http://cdn.avansas.com/assets/53313/cappy-meyve-suyu-kayisi-1-lt-0-zoom.jpg',
                'obs' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'category_id' => 3,
                'subcategory_id' => 9,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Orange Fruit Juice',
                'unitprice' => '1.0',
                'imgurl' => 'https://images.hepsiburada.net/assets/Taris/500/Taris_4791980.jpg',
                'obs' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'category_id' => 4,
                'subcategory_id' => 10,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Black T-Shirt',
                'unitprice' => '20.0',
                'imgurl' => 'https://www.kaft.com/static/images/tee/0628_1.jpg',
                'obs' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'category_id' => 4,
                'subcategory_id' => 10,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Blue T-Shirt',
                'unitprice' => '20.0',
                'imgurl' => 'https://www.kaft.com/static/images/tee/0428_1.jpg',
                'obs' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'category_id' => 4,
                'subcategory_id' => 10,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'White T-Shirt',
                'unitprice' => '20.0',
                'imgurl' => 'https://www.kaft.com/static/images/tee/0603_1.jpg',
                'obs' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'category_id' => 4,
                'subcategory_id' => 11,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Blue Jean',
                'unitprice' => '30.0',
                'imgurl' => 'https://sky-static.mavi.com/sys-master/maviTrImages/h61/h8c/8959419908126/0037823516_image_3.jpg_Default-MainProductImage',
                'obs' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'category_id' => 4,
                'subcategory_id' => 11,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Dark Colored Jean',
                'unitprice' => '30.0',
                'imgurl' => 'https://www.mensfitness.com/sites/mensfitness.com/files/styles/gallery_slideshow_image/public/1280-nudie-lean-jean.jpg?itok=rFDKRlFd',
                'obs' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'category_id' => 4,
                'subcategory_id' => 12,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Winter Jacket',
                'unitprice' => '90.0',
                'imgurl' => 'https://images.thenorthface.com/is/image/TheNorthFace/NF0A2TCN_7D6_hero?$PDP-SCHEMA$',
                'obs' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'category_id' => 4,
                'subcategory_id' => 12,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Leather Jacket',
                'unitprice' => '110.0',
                'imgurl' => 'https://www.revzilla.com/product_images/0091/7906/scorpion1909_leather_jacket_black.jpg',
                'obs' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'category_id' => 4,
                'subcategory_id' => 13,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'White Polo Shirt',
                'unitprice' => '30.99',
                'imgurl' => 'https://www.hemington.com.tr/beyaz-triko-polo-giza-pamuk-tshirt-5513-86-B.jpg',
                'obs' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'category_id' => 4,
                'subcategory_id' => 13,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Fernando Muslera',
                'unitprice' => '999.99',
                'imgurl' => 'http://cdn.gsstore.org/UPLOAD/PRODUCT/thumb/K023-E75365_401_1_large.JPG',
                'obs' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'category_id' => 4,
                'subcategory_id' => 14,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Galatasaray Short',
                'unitprice' => '999.99',
                'imgurl' => 'http://static.barcin.com/web/images/products/659037-628/nike-galatasaray-2015-2016-sezonu-dis-saha-erkek-sort-original-big.jpg',
                'obs' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'category_id' => 4,
                'subcategory_id' => 14,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'LeBron Basketball Short',
                'unitprice' => '40.0',
                'imgurl' => 'http://www.swishbasketball.co.uk/media/catalog/product/cache/1/image/1500x/b661d95dd61f6b4c6be8ac50936dce4f/n/k/nk-718924-657_1.jpg',
                'obs' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'category_id' => 4,
                'subcategory_id' => 15,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'NY Sweatshirt',
                'unitprice' => '50.99',
                'imgurl' => 'https://www.aksesuarix.com/images/products/03/18/21/31821_buyuk.jpg',
                'obs' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'category_id' => 4,
                'subcategory_id' => 15,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Disnet Women Sweatshirt',
                'unitprice' => '45.50',
                'imgurl' => 'https://uniqlo.scene7.com/is/image/UNIQLO/goods_09_182987',
                'obs' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'category_id' => 4,
                'subcategory_id' => 16,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Vans Shoes',
                'unitprice' => '67.30',
                'imgurl' => 'https://m.media-amazon.com/images/G/01/2017/home/october2017/3424427-p-MULTIVIEW._CB514432018_.jpg',
                'obs' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'category_id' => 4,
                'subcategory_id' => 16,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Converse All Star',
                'unitprice' => '55.44',
                'imgurl' => 'https://m.media-amazon.com/images/G/01/zappos/landing/pages/mensclothing/MelodyTest1/MensShoes1._V506596164_.jpg',
                'obs' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'category_id' => 4,
                'subcategory_id' => 17,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Silver Bracelet',
                'unitprice' => '220.0',
                'imgurl' => 'https://www.brighton.com/photos/product/giant/369560S17291/-/size-os.jpg',
                'obs' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'category_id' => 4,
                'subcategory_id' => 17,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Gold Bracelet',
                'unitprice' => '330.0',
                'imgurl' => 'http://scene7.zumiez.com/is/image/zumiez/pdp_hero/The-Gold-Gods-Gold-Cuban-Link-Bracelet-_244592-front.jpg',
                'obs' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'category_id' => 4,
                'subcategory_id' => 17,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Leather Bracelet',
                'unitprice' => '30.0',
                'imgurl' => 'https://images-na.ssl-images-amazon.com/images/I/71TtlBcKFWL._UL1500_.jpg',
                'obs' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'category_id' => 5,
                'subcategory_id' => 18,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Apple iMac i5',
                'unitprice' => '1710.0',
                'imgurl' => 'https://www.apple.com/v/imac/e/images/overview/og_image.png?201709270947',
                'obs' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'category_id' => 5,
                'subcategory_id' => 18,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Apple MacBook i7',
                'unitprice' => '1200.0',
                'imgurl' => 'https://brain-images-ssl.cdn.dixons.com/3/2/10165823/l_10165823_001.jpg',
                'obs' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'category_id' => 5,
                'subcategory_id' => 19,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Galaxy 8inch Tablet',
                'unitprice' => '660.0',
                'imgurl' => 'http://images.samsung.com/is/image/samsung/p5/tr/tablets/galaxy-tab-s2-001.png?$ORIGIN_PNG$',
                'obs' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'category_id' => 5,
                'subcategory_id' => 19,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Asus ZenPad 10inch',
                'unitprice' => '340.0',
                'imgurl' => 'https://images-na.ssl-images-amazon.com/images/I/91aibqJgIDL._SL1500_.jpg',
                'obs' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'category_id' => 5,
                'subcategory_id' => 19,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'iPad Mini 4',
                'unitprice' => '780.0',
                'imgurl' => 'https://www.bhphotovideo.com/images/images2500x2500/apple_mk9n2ll_a_128gb_ipad_mini_4_1185478.jpg',
                'obs' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'category_id' => 5,
                'subcategory_id' => 19,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'iPad Pro',
                'unitprice' => '1110.0',
                'imgurl' => 'https://www.bhphotovideo.com/images/images2500x2500/apple_mlmv2ll_a_9_7_ipad_pro_128gb_1241265.jpg',
                'obs' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'category_id' => 5,
                'subcategory_id' => 20,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Samsung S8',
                'unitprice' => '555.0',
                'imgurl' => 'https://s7d2.scene7.com/is/image/SamsungUS/GS8_Front_20170712?$product-details-jpg$',
                'obs' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'category_id' => 5,
                'subcategory_id' => 20,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'iPhone 7',
                'unitprice' => '660.0',
                'imgurl' => 'https://centrecomstatic.s3.amazonaws.com/images/upload/0038722_0.png',
                'obs' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'category_id' => 5,
                'subcategory_id' => 20,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'iPhone X',
                'unitprice' => '1259.00',
                'imgurl' => 'https://cdn.macrumors.com/article-new/2017/09/iphonexdesign.jpg',
                'obs' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'category_id' => 5,
                'subcategory_id' => 20,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'LG G6',
                'unitprice' => '440.0',
                'imgurl' => 'http://www.lg.com/au/images/smartphones/MD05812152/gallery/G6-medium06.jpg',
                'obs' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'category_id' => 5,
                'subcategory_id' => 20,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Xiaomi Mi Mix 2',
                'unitprice' => '350.0',
                'imgurl' => 'https://image4.geekbuying.com/ggo_pic/2017-09-11/Xiaomi-Mi-Mix-2-5-99-Inch-6GB-64GB-Smartphone-Black-465274-.jpg',
                'obs' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'category_id' => 5,
                'subcategory_id' => 20,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Galaxy Note 8',
                'unitprice' => '880.0',
                'imgurl' => 'https://images-na.ssl-images-amazon.com/images/I/41GZvrGM5bL.jpg',
                'obs' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'category_id' => 5,
                'subcategory_id' => 21,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Samsung 40inch TV',
                'unitprice' => '330.0',
                'imgurl' => 'https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/103/10317/10317673.jpg',
                'obs' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'category_id' => 5,
                'subcategory_id' => 22,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Canon EOS 650D',
                'unitprice' => '925.0',
                'imgurl' => 'https://shop.usa.canon.com/wcsstore/ExtendedSitesCatalogAssetStore/eos-t7i-18-55_1_xl.jpg',
                'obs' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'category_id' => 5,
                'subcategory_id' => 22,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Go Pro 5',
                'unitprice' => '1300.0',
                'imgurl' => 'https://www.bhphotovideo.com/images/images2500x2500/gopro_chdhx_501_hero5_black_1274419.jpg',
                'obs' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'category_id' => 5,
                'subcategory_id' => 22,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Nikon 5600D',
                'unitprice' => '800.0',
                'imgurl' => 'https://cdn-4.nikon-cdn.com/e/Q5NM96RZZo-YRYNeYvAi9beHK4x3L-8go_p7JUL6JpQM8B_IxDfxyg==/Views/1575_D5600_left.png',
                'obs' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'category_id' => 5,
                'subcategory_id' => 23,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Playstation 4 Pro',
                'unitprice' => '420.99',
                'imgurl' => 'https://rukminim1.flixcart.com/image/1408/1408/gamingconsole/g/a/t/playstation-4-ps4-500-sony-dualshock-4-controller-original-imadrhehpvvetkgf.jpeg?q=90',
                'obs' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'category_id' => 5,
                'subcategory_id' => 23,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'FİFA 18',
                'unitprice' => '40.0',
                'imgurl' => 'https://compass-ssl.xbox.com/assets/79/b1/79b130b1-d2a5-4858-98c8-5eecc16902bf.jpg?n=FF18_GLP-Page-Hero-1084_1920x600_02.jpg',
                'obs' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'category_id' => 5,
                'subcategory_id' => 23,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'NBA 2K 18',
                'unitprice' => '40.0',
                'imgurl' => 'https://static-ca.ebgames.ca/images/products/731461/3max.jpg',
                'obs' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'category_id' => 5,
                'subcategory_id' => 23,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Footbal Manager 18',
                'unitprice' => '40.0',
                'imgurl' => 'http://www-footballmanager-com-18-public.s3.amazonaws.com/footballmanager/news/fm_2018_release_date_7.png',
                'obs' => NULL,
            ),
            62 => 
            array (
                'id' => 64,
                'category_id' => 5,
                'subcategory_id' => 23,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Playstation 4 Controller',
                'unitprice' => '30.0',
                'imgurl' => 'http://media.4rgos.it/i/Argos/6257637_R_Z001A?$Web$&$DefaultPDP570$&$WebPDPBadge570$&topright=empty&bottomleft=empty',
                'obs' => NULL,
            ),
            63 => 
            array (
                'id' => 65,
                'category_id' => 5,
                'subcategory_id' => 23,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Call of Duty WW2',
                'unitprice' => '40.0',
                'imgurl' => 'https://img.bolumsonucanavari.com/images/Upload/2dbedeb3-21a7-4294-8940-7ab68832e3f2.jpg',
                'obs' => NULL,
            ),
            64 => 
            array (
                'id' => 66,
                'category_id' => 5,
                'subcategory_id' => 24,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Galaxy Gear S2',
                'unitprice' => '220.0',
                'imgurl' => 'http://media.4rgos.it/i/Argos/5207042_R_Z002A?$Web$&$DefaultPDP570$',
                'obs' => NULL,
            ),
            65 => 
            array (
                'id' => 67,
                'category_id' => 5,
                'subcategory_id' => 24,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Galaxy Gear S3',
                'unitprice' => '330.0',
                'imgurl' => 'http://www.samsung.com/global/galaxy/gear-s3/images/gear-s3-highlights_design_ft.jpg',
                'obs' => NULL,
            ),
            66 => 
            array (
                'id' => 68,
                'category_id' => 5,
                'subcategory_id' => 24,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Apple Watch',
                'unitprice' => '440.0',
                'imgurl' => 'https://brain-images-ssl.cdn.dixons.com/2/9/10151992/l_10151992_001.jpg',
                'obs' => NULL,
            ),
            67 => 
            array (
                'id' => 69,
                'category_id' => 5,
                'subcategory_id' => 24,
                'created_at' => '2023-06-09 12:51:45',
                'updated_at' => NULL,
                'status' => 1,
                'promotional' => 0,
                'name' => 'Xiaomi Mi Band 2',
                'unitprice' => '20.0',
                'imgurl' => 'https://image4.geekbuying.com/ggo_pic/2016-06-03/201606309322239menyh.jpg',
                'obs' => NULL,
            ),
            68 => 
            array (
                'id' => 70,
                'category_id' => 5,
                'subcategory_id' => 5,
                'created_at' => '2023-06-19 15:08:15',
                'updated_at' => '2023-06-19 15:08:15',
                'status' => 1,
                'promotional' => 1,
                'name' => 'Barba Forte',
                'unitprice' => '125.99',
                'imgurl' => 'https://images.tcdn.com.br/img/img_prod/686591/combo_danger_shampoo_condicionador_oleo_barba_forte_3_produtos_43_1_97e7b59b4d9278c9a88cf952cb361c24.jpg',
                'obs' => NULL,
            ),
        ));
        
        
    }
}