<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 25,
                'file_id' => NULL,
                'name' => 'Paulo Sergio',
                'email' => 'dep.limpeza@gmail.com',
                'telefone' => '19991891961',
                'endereco' => NULL,
                'cidade' => 'Localização não informada',
                'rua' => NULL,
                'cidadeufbairrostr' => 'Localização não informada',
                'area_id' => '1,6',
                'categoria' => 'cab',
                'isadmin' => 1,
                'membro' => NULL,
                'concordo' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$nrhNaE5PP51yVuALAab0reSCbTiFBj4obHkkEuR/k3gxY2kElgvjK',
                'menuroles' => 'user',
                'remember_token' => NULL,
                'created_at' => '2023-05-30 17:39:58',
                'status' => 1,
                'updated_at' => '2023-07-12 12:24:38',
                'deleted_at' => NULL,
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
                'player_id' => '264240cc-088a-49d5-bf09-9083238ea805',
                'versionname' => '1.0',
                'versioncode' => '1',
                'token_firebase' => NULL,
                'inicio' => NULL,
                'codigo' => 385443,
                'imagem' => '25.jpg',
                'historico' => 'Tenho alergia de alguns produtos capilares, dermatite de contato ou eczema de contato. Trata-se de uma reação inflamatória na pele devido à exposição a certas substâncias, os alérgenos - receita medica',
                'usernamecad' => NULL,
                'Onesignal_device_id' => '0e2f35b7-d64d-46c8-88a7-89ad3f5b5bc0',
            ),
            1 => 
            array (
                'id' => 26,
                'file_id' => NULL,
                'name' => 'Paulo Souza',
                'email' => 'paulovinteeum@gmail.com',
                'telefone' => '19991891969',
                'endereco' => NULL,
                'cidade' => 'Indaiatuba-SP',
                'rua' => NULL,
                'cidadeufbairrostr' => 'Indaiatuba-SP',
                'area_id' => '1, 2, 3',
                'categoria' => 'cab',
                'isadmin' => 1,
                'membro' => NULL,
                'concordo' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$12$1I2e8wga5VR7kahcw0g1E.Z/1YNAxlQlI6eFQuwmnpvEc8bAywIOO',
                'menuroles' => 'user',
                'remember_token' => NULL,
                'created_at' => '2023-05-30 17:43:55',
                'status' => 1,
                'updated_at' => '2023-06-15 20:51:54',
                'deleted_at' => NULL,
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
                'player_id' => NULL,
                'versionname' => NULL,
                'versioncode' => NULL,
                'token_firebase' => NULL,
                'inicio' => NULL,
                'codigo' => NULL,
                'imagem' => NULL,
                'historico' => NULL,
                'usernamecad' => NULL,
                'Onesignal_device_id' => NULL,
            ),
            2 => 
            array (
                'id' => 27,
                'file_id' => NULL,
                'name' => 'Juliana Silva',
                'email' => 'sistemazenadigital@gmail.com',
                'telefone' => '1999189155',
                'endereco' => NULL,
                'cidade' => 'Indaiatuba',
                'rua' => NULL,
                'cidadeufbairrostr' => NULL,
                'area_id' => '1',
                'categoria' => 'cab',
                'isadmin' => 0,
                'membro' => NULL,
                'concordo' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Zrtb86pw0bIbI263yM.GrO0t81PLVztYTlQIpgdqH5Mh4tlBND5xi',
                'menuroles' => 'user',
                'remember_token' => NULL,
                'created_at' => '2023-05-30 17:43:55',
                'status' => 1,
                'updated_at' => '2023-05-30 17:43:55',
                'deleted_at' => NULL,
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
                'player_id' => NULL,
                'versionname' => NULL,
                'versioncode' => NULL,
                'token_firebase' => NULL,
                'inicio' => NULL,
                'codigo' => NULL,
                'imagem' => NULL,
                'historico' => NULL,
                'usernamecad' => NULL,
                'Onesignal_device_id' => NULL,
            ),
            3 => 
            array (
                'id' => 28,
                'file_id' => NULL,
                'name' => 'Zenete Oliveira',
                'email' => 'artesdazena@gmail.com',
                'telefone' => '19991891962',
                'endereco' => NULL,
                'cidade' => 'Indaiatuba',
                'rua' => NULL,
                'cidadeufbairrostr' => NULL,
                'area_id' => '2',
                'categoria' => 'cab',
                'isadmin' => 0,
                'membro' => NULL,
                'concordo' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Zrtb86pw0bIbI263yM.GrO0t81PLVztYTlQIpgdqH5Mh4tlBND5xi',
                'menuroles' => 'user',
                'remember_token' => NULL,
                'created_at' => '2023-05-30 17:43:55',
                'status' => 1,
                'updated_at' => '2023-05-30 17:43:55',
                'deleted_at' => NULL,
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
                'player_id' => NULL,
                'versionname' => NULL,
                'versioncode' => NULL,
                'token_firebase' => NULL,
                'inicio' => NULL,
                'codigo' => NULL,
                'imagem' => NULL,
                'historico' => NULL,
                'usernamecad' => NULL,
                'Onesignal_device_id' => NULL,
            ),
            4 => 
            array (
                'id' => 29,
                'file_id' => NULL,
                'name' => 'Juliana Oliveira',
                'email' => 'adazena@gmail.com',
                'telefone' => '19991891965',
                'endereco' => NULL,
                'cidade' => 'Indaiatuba',
                'rua' => NULL,
                'cidadeufbairrostr' => NULL,
                'area_id' => '',
                'categoria' => 'cab',
                'isadmin' => 0,
                'membro' => NULL,
                'concordo' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Zrtb86pw0bIbI263yM.GrO0t81PLVztYTlQIpgdqH5Mh4tlBND5xi',
                'menuroles' => 'user',
                'remember_token' => NULL,
                'created_at' => '2023-05-30 17:43:55',
                'status' => 1,
                'updated_at' => '2023-06-18 18:18:06',
                'deleted_at' => NULL,
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
                'player_id' => NULL,
                'versionname' => NULL,
                'versioncode' => NULL,
                'token_firebase' => NULL,
                'inicio' => NULL,
                'codigo' => NULL,
                'imagem' => NULL,
                'historico' => NULL,
                'usernamecad' => NULL,
                'Onesignal_device_id' => NULL,
            ),
            5 => 
            array (
                'id' => 30,
                'file_id' => NULL,
                'name' => 'Véra Lucia Batista',
                'email' => 'vrbatista@gmail.com',
                'telefone' => '19991891960',
                'endereco' => NULL,
                'cidade' => 'Indaiatuba',
                'rua' => NULL,
                'cidadeufbairrostr' => NULL,
                'area_id' => '',
                'categoria' => 'cab',
                'isadmin' => 0,
                'membro' => NULL,
                'concordo' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Zrtb86pw0bIbI263yM.GrO0t81PLVztYTlQIpgdqH5Mh4tlBND5xi',
                'menuroles' => 'user',
                'remember_token' => NULL,
                'created_at' => '2023-05-30 17:43:55',
                'status' => 1,
                'updated_at' => '2023-05-30 17:43:55',
                'deleted_at' => NULL,
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
                'player_id' => NULL,
                'versionname' => NULL,
                'versioncode' => NULL,
                'token_firebase' => NULL,
                'inicio' => NULL,
                'codigo' => NULL,
                'imagem' => NULL,
                'historico' => NULL,
                'usernamecad' => NULL,
                'Onesignal_device_id' => NULL,
            ),
            6 => 
            array (
                'id' => 31,
                'file_id' => NULL,
                'name' => 'Tiago Batista',
                'email' => 'thiagobatista@gmail.com',
                'telefone' => '19991891951',
                'endereco' => NULL,
                'cidade' => 'Localização não informada',
                'rua' => NULL,
                'cidadeufbairrostr' => 'Localização não informada',
                'area_id' => '',
                'categoria' => 'cab',
                'isadmin' => 0,
                'membro' => NULL,
                'concordo' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Zrtb86pw0bIbI263yM.GrO0t81PLVztYTlQIpgdqH5Mh4tlBND5xi',
                'menuroles' => 'user',
                'remember_token' => NULL,
                'created_at' => '2023-05-30 17:43:55',
                'status' => 0,
                'updated_at' => '2023-06-19 12:42:54',
                'deleted_at' => NULL,
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
                'player_id' => NULL,
                'versionname' => NULL,
                'versioncode' => NULL,
                'token_firebase' => NULL,
                'inicio' => NULL,
                'codigo' => NULL,
                'imagem' => NULL,
                'historico' => NULL,
                'usernamecad' => NULL,
                'Onesignal_device_id' => NULL,
            ),
            7 => 
            array (
                'id' => 32,
                'file_id' => NULL,
                'name' => 'Reginaldo Santos',
                'email' => 'rginaldo@gmail.com',
                'telefone' => '1997854321',
                'endereco' => NULL,
                'cidade' => 'Indaiatuba - SP',
                'rua' => NULL,
                'cidadeufbairrostr' => 'Indaiatuba - SP',
                'area_id' => '9,11',
                'categoria' => 'cab',
                'isadmin' => 0,
                'membro' => NULL,
                'concordo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Dt8PAn36F6PXIj/YByvoY.LpmUhsEA3bI4Tp79njEPx8bIOGCDV0S',
                'menuroles' => 'user',
                'remember_token' => NULL,
                'created_at' => '2023-06-18 19:06:09',
                'status' => 1,
                'updated_at' => '2023-06-18 19:06:23',
                'deleted_at' => NULL,
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
                'player_id' => NULL,
                'versionname' => NULL,
                'versioncode' => NULL,
                'token_firebase' => NULL,
                'inicio' => NULL,
                'codigo' => NULL,
                'imagem' => NULL,
                'historico' => NULL,
                'usernamecad' => NULL,
                'Onesignal_device_id' => NULL,
            ),
            8 => 
            array (
                'id' => 39,
                'file_id' => NULL,
                'name' => 'Paulo Senha',
                'email' => 'paulo2@gmail.com',
                'telefone' => '19981916453',
                'endereco' => NULL,
                'cidade' => 'Indaiatuba-SP',
                'rua' => NULL,
                'cidadeufbairrostr' => 'Indaiatuba-SP',
                'area_id' => '1,2,3,4,6,11,12,22,23,24',
                'categoria' => 'cab',
                'isadmin' => 0,
                'membro' => NULL,
                'concordo' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$fJd7Vs9C1lebZgTLtGiCReUoo.d3D7VoLs55FswCe.ZjY/nbMX4zm',
                'menuroles' => 'user',
                'remember_token' => NULL,
                'created_at' => '2023-06-22 20:09:49',
                'status' => 1,
                'updated_at' => '2023-06-23 12:43:09',
                'deleted_at' => NULL,
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
                'player_id' => NULL,
                'versionname' => NULL,
                'versioncode' => NULL,
                'token_firebase' => NULL,
                'inicio' => '01/06/2023',
                'codigo' => NULL,
                'imagem' => '39.jpg',
                'historico' => NULL,
                'usernamecad' => NULL,
                'Onesignal_device_id' => NULL,
            ),
            9 => 
            array (
                'id' => 40,
                'file_id' => NULL,
                'name' => 'Nomer 3',
                'email' => 'paulo3@gmail.com',
                'telefone' => '1992121',
                'endereco' => NULL,
                'cidade' => 'wqqwqw',
                'rua' => NULL,
                'cidadeufbairrostr' => NULL,
                'area_id' => '1, 2, 3',
                'categoria' => 'cab',
                'isadmin' => 0,
                'membro' => NULL,
                'concordo' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$G5t/qflF3kQNOeGYVIMh2eD/KtzuGgLMi9Z26Csj7.S0qm5rVWOSm',
                'menuroles' => 'user',
                'remember_token' => NULL,
                'created_at' => '2023-06-22 20:12:36',
                'status' => 1,
                'updated_at' => '2023-06-22 20:12:36',
                'deleted_at' => NULL,
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
                'player_id' => NULL,
                'versionname' => NULL,
                'versioncode' => NULL,
                'token_firebase' => NULL,
                'inicio' => '01/06/2023',
                'codigo' => NULL,
                'imagem' => NULL,
                'historico' => NULL,
                'usernamecad' => NULL,
                'Onesignal_device_id' => NULL,
            ),
            10 => 
            array (
                'id' => 41,
                'file_id' => NULL,
                'name' => 'Paulo 4',
                'email' => 'paulo4@gmail.com',
                'telefone' => '1989898900',
                'endereco' => NULL,
                'cidade' => 'asasas',
                'rua' => NULL,
                'cidadeufbairrostr' => NULL,
                'area_id' => '1, 2',
                'categoria' => 'cab',
                'isadmin' => 0,
                'membro' => NULL,
                'concordo' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$vw5js.bphrh59qsSQsJ9PetUeXRtzO5ZADvR5eo2IwRNzJZUqPgMW',
                'menuroles' => 'user',
                'remember_token' => NULL,
                'created_at' => '2023-06-22 20:14:39',
                'status' => 1,
                'updated_at' => '2023-06-22 20:14:39',
                'deleted_at' => NULL,
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
                'player_id' => NULL,
                'versionname' => NULL,
                'versioncode' => NULL,
                'token_firebase' => NULL,
                'inicio' => '01/06/2023',
                'codigo' => NULL,
                'imagem' => NULL,
                'historico' => NULL,
                'usernamecad' => NULL,
                'Onesignal_device_id' => NULL,
            ),
            11 => 
            array (
                'id' => 42,
                'file_id' => NULL,
                'name' => 'Paulo 5',
                'email' => 'paulo5@gmail.com',
                'telefone' => '12121212',
                'endereco' => NULL,
                'cidade' => 'hshdsjhsakd',
                'rua' => NULL,
                'cidadeufbairrostr' => NULL,
                'area_id' => '1, 2, 3',
                'categoria' => 'cab',
                'isadmin' => 0,
                'membro' => NULL,
                'concordo' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$LyLe88byq6JlHgBZxVfvh.Vt7.pNImk1.YvhkepMfL8lWhg4Nbg1O',
                'menuroles' => 'user',
                'remember_token' => NULL,
                'created_at' => '2023-06-22 20:17:32',
                'status' => 1,
                'updated_at' => '2023-06-22 20:17:32',
                'deleted_at' => NULL,
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
                'player_id' => NULL,
                'versionname' => NULL,
                'versioncode' => NULL,
                'token_firebase' => NULL,
                'inicio' => '01/06/2023',
                'codigo' => NULL,
                'imagem' => NULL,
                'historico' => NULL,
                'usernamecad' => NULL,
                'Onesignal_device_id' => NULL,
            ),
        ));
        
        
    }
}